title: Blog Exemplo 2
description: "Notas e artigos."
plugins: [jekyll-feed, jekyll-sitemap]
remote_theme: Erick-Lamperouge/estrutura-dos-blogs@main
adsense_client_id: ""
ads: { sidebar_slots: [], in_article_slot: "" }
permalink: /:categories/:title/
feed: { path: feed.xml }
baseurl: "/www.futebolando.github.io" # Deve ser o nome do seu reposit√≥rio
